# Generated by Django 2.2.5 on 2019-09-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190920_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='colum',
            name='home_display',
            field=models.BooleanField(default=False, verbose_name='首页显示'),
        ),
        migrations.AddField(
            model_name='colum',
            name='nav_display',
            field=models.BooleanField(default=False, verbose_name='导航显示'),
        ),
    ]
